Repository ramanbhandari/vamoose, pull requests merged in 2025-02, with the labels that each got.

#38 #9 - Initialize Prisma and create initial db schemas
  README.md
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/prisma/migrations/20250130211033_init/migration.sql
  server/prisma/migrations/migration_lock.toml
  server/prisma/schema.prisma
Labels: setup-persistence

#41 #40 - Create github action workflow to prevent PR merge without Label
  .github/workflows/check-PR-labels.yml
Labels: setup-workflow

#105 Fix PR merge block due to poor label check
  .github/workflows/check-PR-labels.yml
Labels: bug

#98 10 mongodb setup
  server/docker-compose.yml
  server/nodemon.json
  server/package-lock.json
  server/package.json
  server/src/db/.gitkeep
  server/src/db/mongo.ts
  server/src/models/.gitkeep
  server/src/models/Message.ts
  server/src/models/Poll.ts
  server/src/server.ts
Labels: setup-persistence

#108 Fix formatting errors
  server/src/config/prismaClient.ts
  server/src/controllers/tripController.ts
  server/src/interfaces/authInterface.ts
  server/src/interfaces/tripInterface.ts
  server/src/models/tripModels.ts
  server/src/routes/tripRoutes.ts
  server/src/server.ts
  server/src/tests/unit/tripController.test.ts
  server/src/utils/errors.ts
  server/src/utils/prismaErrorHandler.ts
Labels: cleanup

#106 #14 - Set up supabase auth, app themes and login page UI
  frontend/.gitignore
  frontend/app/ThemeProvider.tsx
  frontend/app/dashboard/actions.tsx
  frontend/app/dashboard/messages.ts
  frontend/app/dashboard/page.tsx
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/login/AuthForm.tsx
  frontend/app/login/messages.ts
  frontend/app/login/page.tsx
  frontend/app/page.tsx
  frontend/components/ThemeToggle.tsx
  frontend/middleware.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/tailwind.config.ts
  frontend/theme/theme.ts
  frontend/utils/supabase/client.ts
  frontend/utils/supabase/middleware.ts
  frontend/utils/supabase/server.ts
Labels: Feature - Authentication and Management, Presentation

#110 #107 - Created footer navbar with logout and dark/light mode tooltip
  frontend/app/ThemeProvider.tsx
  frontend/app/dashboard/page.tsx
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/login/AuthForm.tsx
  frontend/components/ThemeToggle.tsx
  frontend/components/footer/Footer.tsx
  frontend/components/navbar/Navbar.tsx
  frontend/theme/theme.ts
Labels: Feature - Trip Dashboard, Presentation

#112 18 - Setup Dashboard UI components
  frontend/app/dashboard/page.tsx
  frontend/components/CreateTripButton.tsx
  frontend/components/TripCard.tsx
  frontend/components/blocks/Backgrounds/GridMotion/GridMotion.tsx
  frontend/components/footer/Footer.tsx
  frontend/jsrepo.json
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/public/card_def.jpg
Labels: Feature - Trip Dashboard, Presentation

#117 116 create hamburger top navbar
  frontend/components/ThemeToggle.tsx
  frontend/components/navbar/Navbar.tsx
  frontend/components/navbar/hamAnimIcon.tsx
Labels: Feature - Authentication and Management, Presentation

#121 33 UI for trip summary page
  frontend/app/globals.css
  frontend/app/trips/[:tripId]/page.tsx
  frontend/app/trips/[:tripId]/sections/Activities.tsx
  frontend/app/trips/[:tripId]/sections/Dates.tsx
  frontend/app/trips/[:tripId]/sections/Destinations.tsx
  frontend/app/trips/[:tripId]/sections/Expenses.tsx
  frontend/app/trips/[:tripId]/sections/Itinerary.tsx
  frontend/app/trips/[:tripId]/sections/Overview.tsx
  frontend/app/trips/[:tripId]/sections/PackingList.tsx
  frontend/app/trips/[:tripId]/sections/Polls.tsx
  frontend/app/trips/[:tripId]/sections/Stays.tsx
  frontend/app/trips/[:tripId]/sections/TripMembers.tsx
  frontend/components/blocks/Components/Dock/Dock.tsx
  frontend/components/navbar/Navbar.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/theme/theme.ts
Labels: Feature - Trip Dashboard, Presentation

#126 Integrates fetch Trips API with Dashboard and Trip Summary overview.
  frontend/app/dashboard/page.tsx
  frontend/app/trips/[tripId]/page.tsx
  frontend/app/trips/[tripId]/sections/Activities.tsx
  frontend/app/trips/[tripId]/sections/Dates.tsx
  frontend/app/trips/[tripId]/sections/Destinations.tsx
  frontend/app/trips/[tripId]/sections/Expenses.tsx
  frontend/app/trips/[tripId]/sections/Itinerary.tsx
  frontend/app/trips/[tripId]/sections/Overview.tsx
  frontend/app/trips/[tripId]/sections/PackingList.tsx
  frontend/app/trips/[tripId]/sections/Polls.tsx
  frontend/app/trips/[tripId]/sections/Stays.tsx
  frontend/app/trips/[tripId]/sections/TripMembers.tsx
  frontend/app/trips/create/DestinationField.tsx
  frontend/app/trips/create/page.tsx
  frontend/components/TripCard.tsx
  frontend/utils/apiClient.ts
  frontend/utils/supabase/client.ts
Labels: Feature - Trip Dashboard, Presentation

#129 25 api to handle invitations
  server/jest.config.js
  server/prisma/migrations/20250219000224_update_trip_invitee_model/migration.sql
  server/prisma/migrations/20250219215301_update_schema_to_link_users_to_trip/migration.sql
  server/prisma/migrations/20250222165336_changed_invite_token/migration.sql
  server/prisma/schema.prisma
  server/src/config/.gitkeep
  server/src/controllers/invitee.controller.ts
  server/src/interfaces/interfaces.ts
  server/src/middleware/invitee.validators.ts
  server/src/models/invitee.model.ts
  server/src/models/member.model.ts
  server/src/models/message.model.ts
  server/src/models/poll.model.ts
  server/src/models/trip.model.ts
  server/src/models/user.model.ts
  server/src/routes/appRouter.ts
  server/src/routes/invitee.routes.ts
  server/src/server.ts
  server/src/tests/unit/invite.tests/invitee.controller.test.ts
  server/src/utils/.gitkeep
Labels: Business

#135 Fix infinite Trip fetch API calls
  frontend/app/dashboard/page.tsx
  frontend/app/trips/[tripId]/sections/Overview.tsx
  frontend/app/trips/create/page.tsx
  frontend/components/blocks/Backgrounds/GridMotion/GridMotion.tsx
  frontend/components/blocks/Components/Dock/Dock.tsx
Labels: bug

#136 122 create an endpoint to fetch an expense
  server/.prettierrc
  server/docker-compose.yml
  server/jest.config.js
  server/nodemon.json
  server/package-lock.json
  server/package.json
  server/src/controllers/expense.controller.ts
  server/src/controllers/invitee.controller.ts
  server/src/middleware/expense.validators.ts
  server/src/middleware/invitee.validators.ts
  server/src/models/expense.model.ts
  server/src/models/invitee.model.ts
  server/src/routes/expense.routes.ts
  server/src/routes/invitee.routes.ts
  server/src/server.ts
  server/src/tests/unit/expense.tests/expense.controller.test.ts
  server/src/tests/unit/expense.tests/expense.validators.test.ts
  server/src/tests/unit/invite.tests/invitee.controller.test.ts
  server/tsconfig.json
Labels: Feature - Group Expense Tracker, Business

#154 Minor frontend fixes
  frontend/app/dashboard/page.tsx
  frontend/app/login/AuthForm.tsx
  frontend/app/trips/[tripId]/page.tsx
  frontend/app/trips/[tripId]/sections/Overview.tsx
  frontend/app/trips/create/page.tsx
  frontend/components/TripCard.tsx
  frontend/components/navbar/Navbar.tsx
  frontend/public/dashboard/dashboard_22.jpg
  frontend/public/dashboard/dashboard_23.jpg
Labels: bug, Feature - Trip Dashboard, Presentation

#153 123 create endpoints to delete expenses
  server/package-lock.json
  server/package.json
  server/src/controllers/expense.controller.ts
  server/src/middleware/expense.validators.ts
  server/src/models/expense.model.ts
  server/src/models/expenseShare.model.ts
  server/src/routes/expense.routes.ts
  server/src/tests/unit/expense.tests/expense.controller.test.ts
  server/src/tests/unit/expense.tests/expense.validators.test.ts
Labels: Feature - Group Expense Tracker

#155 23 UI for inviting
  frontend/app/trips/[tripId]/page.tsx
  frontend/app/trips/[tripId]/sections/Overview.tsx
  frontend/app/trips/[tripId]/sections/TripMembers.tsx
  frontend/components/InviteModal.tsx
  server/src/controllers/invitee.controller.ts
  server/src/tests/unit/invite.tests/invitee.validators.test.ts
Labels: Feature - Trip Dashboard, Presentation, cleanup

#159 Added checks and tests for multiple expenses
  server/src/controllers/expense.controller.ts
  server/src/models/expense.model.ts
  server/src/models/expenseShare.model.ts
  server/src/tests/unit/expense.tests/expense.controller.test.ts
Labels: Feature - Group Expense Tracker, Business

#164 29 modify or delete existing UI form for trip
  frontend/.eslintrc.json
  frontend/.prettierrc
  frontend/app/dashboard/page.tsx
  frontend/app/globals.css
  frontend/app/layout.tsx
  frontend/app/trips/[tripId]/page.tsx
  frontend/app/trips/[tripId]/sections/Overview.tsx
  frontend/app/trips/[tripId]/sections/TripMembers.tsx
  frontend/components/ConfirmationDialog.tsx
  frontend/components/InviteModal.tsx
  frontend/components/ThemeToggle.tsx
  frontend/components/TripCard.tsx
  frontend/components/navbar/hamAnimIcon.tsx
  frontend/components/trips/Overview/BudgetDonut.tsx
  frontend/package-lock.json
  frontend/package.json
  server/package-lock.json
Labels: Feature - Trip Dashboard, Presentation

#173 44-45-Create Expense UI to add expense and filters
  frontend/app/layout.tsx
  frontend/app/trips/[tripId]/page.tsx
  frontend/app/trips/[tripId]/sections/Expenses.tsx
  frontend/app/trips/[tripId]/sections/Overview.tsx
  frontend/components/NotificationSnackbar.tsx
  frontend/components/trips/Overview/BudgetDonut.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/stores/notification-store.ts
  frontend/stores/trip-store.ts
Labels: Feature - Group Expense Tracker, Presentation

#177 176 - Adds current trip section to dashboard.
  frontend/app/dashboard/Skeleton.tsx
  frontend/app/dashboard/page.tsx
Labels: enhancement, Feature - Trip Dashboard, Presentation

#179 178 - Implements delete single or multiple expenses
  frontend/app/trips/[tripId]/sections/Expenses.tsx
  frontend/app/trips/create/page.tsx
  frontend/components/NotificationSnackbar.tsx
  frontend/components/trips/Overview/BudgetDonut.tsx
  frontend/stores/notification-store.ts
  frontend/stores/trip-store.ts
Labels: Feature - Group Expense Tracker, Presentation

#175 174 update server tsconfig
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/src/controllers/expense.controller.ts
  server/src/controllers/invitee.controller.ts
  server/src/controllers/member.controller.ts
  server/src/controllers/trip.controller.ts
  server/src/models/expense.model.ts
  server/src/models/expenseShare.model.ts
  server/src/models/invitee.model.ts
  server/src/models/member.model.ts
  server/src/models/trip.model.ts
  server/src/models/user.model.ts
  server/src/routes/appRouter.ts
  server/src/routes/expense.routes.ts
  server/src/routes/invitee.routes.ts
  server/src/routes/member.routes.ts
  server/src/routes/trip.routes.ts
  server/src/server.ts
  server/src/tests/unit/authMiddleware.test.ts
  server/src/tests/unit/expense.tests/expense.controller.test.ts
  server/src/tests/unit/expense.tests/expense.validators.test.ts
  server/src/tests/unit/invite.tests/invitee.controller.test.ts
  server/src/tests/unit/invite.tests/invitee.validators.test.ts
  server/src/tests/unit/member.tests/member.controller.test.ts
  server/src/tests/unit/member.tests/member.validators.test.ts
  server/src/tests/unit/trip.tests/trip.controller.test.ts
  server/src/tests/unit/trip.tests/trip.validators.test.ts
  server/src/tests/unit/validationErrorHandler.test.ts
  server/src/utils/errorHandlers.ts
  server/tsconfig.json
Labels: bug, Business

#181 Dockerize the app
  frontend/Dockerfile
  frontend/README.md
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
  server/Dockerfile
  server/prisma/schema.prisma
Labels: setup-workflow

#184 Merge: Dev to UAT
  frontend/Dockerfile
  frontend/README.md
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
  server/Dockerfile
  server/prisma/schema.prisma
Labels: dev-to-uat

#185 Merge UAT to MAIN
  frontend/Dockerfile
  frontend/README.md
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
  server/Dockerfile
  server/prisma/schema.prisma
Labels: UAT-to-MAIN

#186 Update tsconfig to exclude prod build
  server/tsconfig.json
Labels: Business

#187 DEV to UAT
  server/tsconfig.json
Labels: dev-to-uat

#188 Uat to main
  server/tsconfig.json
Labels: UAT-to-MAIN

#189 Remove production flag from npm ci to include dev dependencies
  server/Dockerfile
Labels: Business
